//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Tools {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SFBTpFB2Dublicator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SFBTpFB2Dublicator() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Main.Tools.SFBTpFB2Dublicator", typeof(SFBTpFB2Dublicator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnOpenDir_Image {
            get {
                object obj = ResourceManager.GetObject("btnOpenDir.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=252,Y=13}.
        /// </summary>
        internal static System.Drawing.Point cmsFB2_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("cmsFB2.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=917,Y=9}.
        /// </summary>
        internal static System.Drawing.Point CommandToolStrip_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("CommandToolStrip.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=348,Y=9}.
        /// </summary>
        internal static System.Drawing.Point fbdSaveList_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("fbdSaveList.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=139,Y=9}.
        /// </summary>
        internal static System.Drawing.Point fbdScanDir_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("fbdScanDir.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImageListStreamer.
        /// </summary>
        internal static System.Windows.Forms.ImageListStreamer imageListDup_ImageStream {
            get {
                object obj = ResourceManager.GetObject("imageListDup.ImageStream", resourceCulture);
                return ((System.Windows.Forms.ImageListStreamer)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=586,Y=10}.
        /// </summary>
        internal static System.Drawing.Point imageListDup_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("imageListDup.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap picBoxSTICover_ErrorImage {
            get {
                object obj = ResourceManager.GetObject("picBoxSTICover.ErrorImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap picBoxTICover_ErrorImage {
            get {
                object obj = ResourceManager.GetObject("picBoxTICover.ErrorImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=727,Y=9}.
        /// </summary>
        internal static System.Drawing.Point sfdList_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("sfdList.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=468,Y=10}.
        /// </summary>
        internal static System.Drawing.Point sfdLoadList_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("sfdLoadList.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=17,Y=7}.
        /// </summary>
        internal static System.Drawing.Point ssProgress_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("ssProgress.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STISaveSelectedCoverButton_Image {
            get {
                object obj = ResourceManager.GetObject("STISaveSelectedCoverButton.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TISaveSelectedCoverButton_Image {
            get {
                object obj = ResourceManager.GetObject("TISaveSelectedCoverButton.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButtonCopyCheckedFb2To_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButtonCopyCheckedFb2To.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButtonDiffFB2_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButtonDiffFB2.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButtonEditBookName_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButtonEditBookName.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButtonEditDescription_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButtonEditDescription.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButtonEditInFB2Editor_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButtonEditInFB2Editor.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButtonEditInTextEditor_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButtonEditInTextEditor.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButtonViewInReader_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButtonViewInReader.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripDropDownButtonDeleteCheckedFb2_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButtonDeleteCheckedFb2.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripDropDownButtonEditAuthors_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButtonEditAuthors.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripDropDownButtonEditGenres_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButtonEditGenres.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripDropDownButtonMoveCheckedFb2To_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButtonMoveCheckedFb2To.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripDropDownButtonNewID_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripDropDownButtonNewID.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripMenuItem11_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripMenuItem11.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsbtnDupCurrentSaveList_Image {
            get {
                object obj = ResourceManager.GetObject("tsbtnDupCurrentSaveList.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsbtnDupOpenList_Image {
            get {
                object obj = ResourceManager.GetObject("tsbtnDupOpenList.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsbtnDupSaveList_Image {
            get {
                object obj = ResourceManager.GetObject("tsbtnDupSaveList.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsbtnSearchDubls_Image {
            get {
                object obj = ResourceManager.GetObject("tsbtnSearchDubls.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsbtnSearchFb2DupRenew_Image {
            get {
                object obj = ResourceManager.GetObject("tsbtnSearchFb2DupRenew.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=823,Y=9}.
        /// </summary>
        internal static System.Drawing.Point tsDup_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tsDup.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsmiCheckedAll_Image {
            get {
                object obj = ResourceManager.GetObject("tsmiCheckedAll.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsmiCheckedAllInGroup_Image {
            get {
                object obj = ResourceManager.GetObject("tsmiCheckedAllInGroup.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsmiCopyCheckedFb2To_Image {
            get {
                object obj = ResourceManager.GetObject("tsmiCopyCheckedFb2To.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsmiDeleteCheckedFb2_Image {
            get {
                object obj = ResourceManager.GetObject("tsmiDeleteCheckedFb2.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsmiDiffFB2_Image {
            get {
                object obj = ResourceManager.GetObject("tsmiDiffFB2.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsmiEditAuthors_Image {
            get {
                object obj = ResourceManager.GetObject("tsmiEditAuthors.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsmiEditDescription_Image {
            get {
                object obj = ResourceManager.GetObject("tsmiEditDescription.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsmiEditGenres_Image {
            get {
                object obj = ResourceManager.GetObject("tsmiEditGenres.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsmiEditInFB2Editor_Image {
            get {
                object obj = ResourceManager.GetObject("tsmiEditInFB2Editor.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsmiEditInTextEditor_Image {
            get {
                object obj = ResourceManager.GetObject("tsmiEditInTextEditor.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsmiMoveCheckedFb2To_Image {
            get {
                object obj = ResourceManager.GetObject("tsmiMoveCheckedFb2To.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsmiOpenFileDir_Image {
            get {
                object obj = ResourceManager.GetObject("tsmiOpenFileDir.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsmiSaveAllCheckedItemToFile_Image {
            get {
                object obj = ResourceManager.GetObject("tsmiSaveAllCheckedItemToFile.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsmiUnCheckedAll_Image {
            get {
                object obj = ResourceManager.GetObject("tsmiUnCheckedAll.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsmiValidate_Image {
            get {
                object obj = ResourceManager.GetObject("tsmiValidate.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsmiViewInReader_Image {
            get {
                object obj = ResourceManager.GetObject("tsmiViewInReader.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
