//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Tools {
	using System;
	
	
	/// <summary>
	///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
	/// </summary>
	// Этот класс создан автоматически классом StronglyTypedResourceBuilder
	// с помощью такого средства, как ResGen или Visual Studio.
	// Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
	// с параметром /str или перестройте свой проект VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class SFBTpFB2Dublicator {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal SFBTpFB2Dublicator() {
		}
		
		/// <summary>
		///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Main.Tools.SFBTpFB2Dublicator", typeof(SFBTpFB2Dublicator).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Перезаписывает свойство CurrentUICulture текущего потока для всех
		///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap btnOpenDir_Image {
			get {
				object obj = ResourceManager.GetObject("btnOpenDir.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Windows.Forms.ImageListStreamer.
		/// </summary>
		internal static System.Windows.Forms.ImageListStreamer imageListDup_ImageStream {
			get {
				object obj = ResourceManager.GetObject("imageListDup.ImageStream", resourceCulture);
				return ((System.Windows.Forms.ImageListStreamer)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap picBoxSTICover_ErrorImage {
			get {
				object obj = ResourceManager.GetObject("picBoxSTICover.ErrorImage", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap picBoxTICover_ErrorImage {
			get {
				object obj = ResourceManager.GetObject("picBoxTICover.ErrorImage", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsbtnDupOpenList_Image {
			get {
				object obj = ResourceManager.GetObject("tsbtnDupOpenList.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsbtnDupSaveList_Image {
			get {
				object obj = ResourceManager.GetObject("tsbtnDupSaveList.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsbtnSearchDubls_Image {
			get {
				object obj = ResourceManager.GetObject("tsbtnSearchDubls.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsbtnSearchFb2DupRenew_Image {
			get {
				object obj = ResourceManager.GetObject("tsbtnSearchFb2DupRenew.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsmiAllFilesInGroupReValidate_Image {
			get {
				object obj = ResourceManager.GetObject("tsmiAllFilesInGroupReValidate.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsmiAllGroupsReValidate_Image {
			get {
				object obj = ResourceManager.GetObject("tsmiAllGroupsReValidate.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsmiCheckedAll_Image {
			get {
				object obj = ResourceManager.GetObject("tsmiCheckedAll.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsmiCheckedAllInGroup_Image {
			get {
				object obj = ResourceManager.GetObject("tsmiCheckedAllInGroup.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsmiCopyCheckedFb2To_Image {
			get {
				object obj = ResourceManager.GetObject("tsmiCopyCheckedFb2To.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsmiDeleteCheckedFb2_Image {
			get {
				object obj = ResourceManager.GetObject("tsmiDeleteCheckedFb2.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsmiDeleteFileFromDisk_Image {
			get {
				object obj = ResourceManager.GetObject("tsmiDeleteFileFromDisk.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsmiDiffFB2_Image {
			get {
				object obj = ResourceManager.GetObject("tsmiDiffFB2.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsmiEditDescription_Image {
			get {
				object obj = ResourceManager.GetObject("tsmiEditDescription.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsmiEditInFB2Editor_Image {
			get {
				object obj = ResourceManager.GetObject("tsmiEditInFB2Editor.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsmiEditInTextEditor_Image {
			get {
				object obj = ResourceManager.GetObject("tsmiEditInTextEditor.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsmiFileReValidate_Image {
			get {
				object obj = ResourceManager.GetObject("tsmiFileReValidate.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsmiMoveCheckedFb2To_Image {
			get {
				object obj = ResourceManager.GetObject("tsmiMoveCheckedFb2To.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsmiOpenFileDir_Image {
			get {
				object obj = ResourceManager.GetObject("tsmiOpenFileDir.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsmiSaveAllCheckedItemToFile_Image {
			get {
				object obj = ResourceManager.GetObject("tsmiSaveAllCheckedItemToFile.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsmiUnCheckedAll_Image {
			get {
				object obj = ResourceManager.GetObject("tsmiUnCheckedAll.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap tsmiViewInReader_Image {
			get {
				object obj = ResourceManager.GetObject("tsmiViewInReader.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
